// export const chefOfTheWeekRestaurants: Restaurant[] = [
//     {
//         _id: "1",
//         type: "restaurant",
//         name: "Onza",
//     },
//     {
//         _id: "2",
//         type: "restaurant",
//         name: "Kitchen Market",
//     },
//     {
//         _id: "3",
//         type: "restaurant",
//         name: "Mashya",
//     },
// ];
// export const popularRestaurants: Restaurant[] = [
//     {
//         _Id: "4",
//         type: "restaurant",
//         name: "Claro",
//         chef: "Ran Shmueli",
//         stars: 4,
//     },
//     {
//         _Id: "5",
//         type: "restaurant",
//         name: "Lumina",
//         chef: "Meir Adoni",
//         stars: 3,
//     },
//     {
//         _Id: "6",
//         type: "restaurant",
//         name: "Tiger Lilly",
//         chef: "Yanir Green",
//         stars: 4,
//     },
// ];
// export const bestDishes: Dish[] = [
//     {
//         _Id: "A",
//         type: "dish",
//         name: "Pad Ki Mao",
//         ingredients:
//             "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut",
//         special: "spicy",
//         price: 88,
//         restaurantId: "4",
//     },
//     {
//         _Id: "B",
//         type: "dish",
//         name: "Garbanzo Frito",
//         ingredients:
//             "Polenta fingers, veal cheek, magic chili cured lemon cream, yellow laksa",
//         price: 78,
//         restaurantId: "4",
//     },
//     {
//         _Id: "C",
//         type: "dish",
//         name: "Smoked Pizza",
//         ingredients: 'Basil dough, cashew "butter", demi-glace, bison & radish',
//         special: "vegan",
//         price: 98,
//         restaurantId: "4",
//     },
// ];
// export const allrestaurants: Restaurant[] = [
//     {
//         _Id: "4",
//         type: "restaurant",
//         name: "Claro",
//         chef: "Ran Shmueli",
//         stars: 4,
//         faundationDate: new Date("2023-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "7",
//         type: "restaurant",
//         name: "Kab Kem",
//         chef: "Meir Adoni",
//         stars: 3,
//         faundationDate: new Date("2023-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "8",
//         type: "restaurant",
//         name: "Messa",
//         chef: "Aviv Moshe",
//         stars: 1,
//         faundationDate: new Date("2023-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "9",
//         type: "restaurant",
//         name: "Nitan Thi",
//         chef: "Shahaf Shabtay",
//         stars: 1,
//         faundationDate: new Date("2023-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "6",
//         type: "restaurant",
//         name: "Tiger Lilly",
//         chef: "Yanir Green",
//         stars: 4,
//         faundationDate: new Date("2023-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "10",
//         type: "restaurant",
//         name: "Ya Pan",
//         chef: "Yuval Ben Moshe",
//         stars: 5,
//         faundationDate: new Date("2022-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "11",
//         type: "restaurant",
//         name: "MI MA",
//         chef: "Shahar Saadon",
//         stars: 4,
//         faundationDate: new Date("2022-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "12",
//         type: "restaurant",
//         name: "MI ME",
//         chef: "René Descartes ",
//         stars: 5,
//         faundationDate: new Date("2022-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
//     {
//         _Id: "13",
//         type: "restaurant",
//         name: "MI MU",
//         chef: "Dekel",
//         stars: 3,
//         faundationDate: new Date("2022-01-15"),
//         openHoures: [
//             "09:00-21:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-17:00",
//             "09:00-21:00",
//             "09:00-21:00",
//             "09:00-21:00",
//         ],
//         dishes: [
//             {
//                 _Id: "A",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "B",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "C",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Breakfast",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "D",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "E",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "F",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Lanch",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "G",
//                 type: "dish",
//                 name: "Pad Ki Mao",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 88,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "H",
//                 type: "dish",
//                 name: "Ta Ma La Ko",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//             {
//                 _Id: "I",
//                 type: "dish",
//                 name: "Red Farm",
//                 ingredients:
//                     "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
//                 price: 65,
//                 dishType: "Dinner",
//                 restaurantId: "4",
//             },
//         ],
//     },
// ];
